/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthletePerformanceRouteImport } from './routes/athlete-performance'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as RegisterAthleteRouteImport } from './routes/register-athlete'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SelectAthleteRouteImport } from './routes/select-athlete'
import { Route as SelectTestRouteImport } from './routes/select-test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BatteryIndexRouteImport } from './routes/battery.index'
import { Route as BatteryTestIdRouteImport } from './routes/battery.$testId'
import { Route as BatteryTestIdIndexRouteImport } from './routes/battery.$testId.index'
import { Route as BatteryTestIdProcessingRouteImport } from './routes/battery.$testId.processing'
import { Route as BatteryTestIdRecordRouteImport } from './routes/battery.$testId.record'
import { Route as BatteryTestIdResultRouteImport } from './routes/battery.$testId.result'
import { Route as BatteryTestIdUploadRouteImport } from './routes/battery.$testId.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePerformanceRoute = AthletePerformanceRouteImport.update({
  id: '/athlete-performance',
  path: '/athlete-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAthleteRoute = RegisterAthleteRouteImport.update({
  id: '/register-athlete',
  path: '/register-athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectAthleteRoute = SelectAthleteRouteImport.update({
  id: '/select-athlete',
  path: '/select-athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTestRoute = SelectTestRouteImport.update({
  id: '/select-test',
  path: '/select-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryIndexRoute = BatteryIndexRouteImport.update({
  id: '/battery/',
  path: '/battery/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryTestIdRoute = BatteryTestIdRouteImport.update({
  id: '/battery/$testId',
  path: '/battery/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryTestIdIndexRoute = BatteryTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatteryTestIdRoute,
} as any)
const BatteryTestIdProcessingRoute = BatteryTestIdProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => BatteryTestIdRoute,
} as any)
const BatteryTestIdRecordRoute = BatteryTestIdRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => BatteryTestIdRoute,
} as any)
const BatteryTestIdResultRoute = BatteryTestIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => BatteryTestIdRoute,
} as any)
const BatteryTestIdUploadRoute = BatteryTestIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => BatteryTestIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/camera': typeof CameraRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register-athlete': typeof RegisterAthleteRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/select-athlete': typeof SelectAthleteRoute
  '/select-test': typeof SelectTestRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/battery/$testId': typeof BatteryTestIdRouteWithChildren
  '/battery/': typeof BatteryIndexRoute
  '/battery/$testId/processing': typeof BatteryTestIdProcessingRoute
  '/battery/$testId/record': typeof BatteryTestIdRecordRoute
  '/battery/$testId/result': typeof BatteryTestIdResultRoute
  '/battery/$testId/upload': typeof BatteryTestIdUploadRoute
  '/battery/$testId/': typeof BatteryTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/camera': typeof CameraRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register-athlete': typeof RegisterAthleteRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/select-athlete': typeof SelectAthleteRoute
  '/select-test': typeof SelectTestRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/battery': typeof BatteryIndexRoute
  '/battery/$testId/processing': typeof BatteryTestIdProcessingRoute
  '/battery/$testId/record': typeof BatteryTestIdRecordRoute
  '/battery/$testId/result': typeof BatteryTestIdResultRoute
  '/battery/$testId/upload': typeof BatteryTestIdUploadRoute
  '/battery/$testId': typeof BatteryTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/camera': typeof CameraRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register-athlete': typeof RegisterAthleteRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/select-athlete': typeof SelectAthleteRoute
  '/select-test': typeof SelectTestRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/battery/$testId': typeof BatteryTestIdRouteWithChildren
  '/battery/': typeof BatteryIndexRoute
  '/battery/$testId/processing': typeof BatteryTestIdProcessingRoute
  '/battery/$testId/record': typeof BatteryTestIdRecordRoute
  '/battery/$testId/result': typeof BatteryTestIdResultRoute
  '/battery/$testId/upload': typeof BatteryTestIdUploadRoute
  '/battery/$testId/': typeof BatteryTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athlete-performance'
    | '/camera'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register-athlete'
    | '/report'
    | '/result'
    | '/select-athlete'
    | '/select-test'
    | '/settings'
    | '/auth/callback'
    | '/battery/$testId'
    | '/battery/'
    | '/battery/$testId/processing'
    | '/battery/$testId/record'
    | '/battery/$testId/result'
    | '/battery/$testId/upload'
    | '/battery/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athlete-performance'
    | '/camera'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register-athlete'
    | '/report'
    | '/result'
    | '/select-athlete'
    | '/select-test'
    | '/settings'
    | '/auth/callback'
    | '/battery'
    | '/battery/$testId/processing'
    | '/battery/$testId/record'
    | '/battery/$testId/result'
    | '/battery/$testId/upload'
    | '/battery/$testId'
  id:
    | '__root__'
    | '/'
    | '/athlete-performance'
    | '/camera'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register-athlete'
    | '/report'
    | '/result'
    | '/select-athlete'
    | '/select-test'
    | '/settings'
    | '/auth/callback'
    | '/battery/$testId'
    | '/battery/'
    | '/battery/$testId/processing'
    | '/battery/$testId/record'
    | '/battery/$testId/result'
    | '/battery/$testId/upload'
    | '/battery/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthletePerformanceRoute: typeof AthletePerformanceRoute
  CameraRoute: typeof CameraRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  RegisterAthleteRoute: typeof RegisterAthleteRoute
  ReportRoute: typeof ReportRoute
  ResultRoute: typeof ResultRoute
  SelectAthleteRoute: typeof SelectAthleteRoute
  SelectTestRoute: typeof SelectTestRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BatteryTestIdRoute: typeof BatteryTestIdRouteWithChildren
  BatteryIndexRoute: typeof BatteryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-performance': {
      id: '/athlete-performance'
      path: '/athlete-performance'
      fullPath: '/athlete-performance'
      preLoaderRoute: typeof AthletePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-athlete': {
      id: '/register-athlete'
      path: '/register-athlete'
      fullPath: '/register-athlete'
      preLoaderRoute: typeof RegisterAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-athlete': {
      id: '/select-athlete'
      path: '/select-athlete'
      fullPath: '/select-athlete'
      preLoaderRoute: typeof SelectAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-test': {
      id: '/select-test'
      path: '/select-test'
      fullPath: '/select-test'
      preLoaderRoute: typeof SelectTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery/': {
      id: '/battery/'
      path: '/battery'
      fullPath: '/battery/'
      preLoaderRoute: typeof BatteryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery/$testId': {
      id: '/battery/$testId'
      path: '/battery/$testId'
      fullPath: '/battery/$testId'
      preLoaderRoute: typeof BatteryTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery/$testId/': {
      id: '/battery/$testId/'
      path: '/'
      fullPath: '/battery/$testId/'
      preLoaderRoute: typeof BatteryTestIdIndexRouteImport
      parentRoute: typeof BatteryTestIdRoute
    }
    '/battery/$testId/processing': {
      id: '/battery/$testId/processing'
      path: '/processing'
      fullPath: '/battery/$testId/processing'
      preLoaderRoute: typeof BatteryTestIdProcessingRouteImport
      parentRoute: typeof BatteryTestIdRoute
    }
    '/battery/$testId/record': {
      id: '/battery/$testId/record'
      path: '/record'
      fullPath: '/battery/$testId/record'
      preLoaderRoute: typeof BatteryTestIdRecordRouteImport
      parentRoute: typeof BatteryTestIdRoute
    }
    '/battery/$testId/result': {
      id: '/battery/$testId/result'
      path: '/result'
      fullPath: '/battery/$testId/result'
      preLoaderRoute: typeof BatteryTestIdResultRouteImport
      parentRoute: typeof BatteryTestIdRoute
    }
    '/battery/$testId/upload': {
      id: '/battery/$testId/upload'
      path: '/upload'
      fullPath: '/battery/$testId/upload'
      preLoaderRoute: typeof BatteryTestIdUploadRouteImport
      parentRoute: typeof BatteryTestIdRoute
    }
  }
}

interface BatteryTestIdRouteChildren {
  BatteryTestIdProcessingRoute: typeof BatteryTestIdProcessingRoute
  BatteryTestIdRecordRoute: typeof BatteryTestIdRecordRoute
  BatteryTestIdResultRoute: typeof BatteryTestIdResultRoute
  BatteryTestIdUploadRoute: typeof BatteryTestIdUploadRoute
  BatteryTestIdIndexRoute: typeof BatteryTestIdIndexRoute
}

const BatteryTestIdRouteChildren: BatteryTestIdRouteChildren = {
  BatteryTestIdProcessingRoute: BatteryTestIdProcessingRoute,
  BatteryTestIdRecordRoute: BatteryTestIdRecordRoute,
  BatteryTestIdResultRoute: BatteryTestIdResultRoute,
  BatteryTestIdUploadRoute: BatteryTestIdUploadRoute,
  BatteryTestIdIndexRoute: BatteryTestIdIndexRoute,
}

const BatteryTestIdRouteWithChildren = BatteryTestIdRoute._addFileChildren(
  BatteryTestIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthletePerformanceRoute: AthletePerformanceRoute,
  CameraRoute: CameraRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  RegisterAthleteRoute: RegisterAthleteRoute,
  ReportRoute: ReportRoute,
  ResultRoute: ResultRoute,
  SelectAthleteRoute: SelectAthleteRoute,
  SelectTestRoute: SelectTestRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BatteryTestIdRoute: BatteryTestIdRouteWithChildren,
  BatteryIndexRoute: BatteryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
